development:
  host: localhost
  database: heroku_app4117392
  raise_not_found_error: false

test:
  host: localhost
  database: playlists_development
  raise_not_found_error: false

production:
  #uri: <%= ENV['MONGOLAB_URI'] %>
  uri: 'mongodb://heroku_app4117392:lebq7rjatclopleg65133sv7h8@ds033217.mongolab.com:33217/heroku_app4117392'
